apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wazuh.fullname" . }}-cert-generator
  namespace: {{ include "wazuh.namespace" . }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: {{ include "wazuh.fullname" . }}-cert-generator
      labels:
        {{- include "wazuh.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "wazuh.serviceAccountName" . }}
      containers:
        - name: cert-generator
          image: alpine/openssl:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Generating Wazuh certificates..."
              
              # Create temp directory
              mkdir -p /tmp/certs
              cd /tmp/certs
              
              # Generate Root CA
              echo "1. Generating Root CA..."
              openssl genrsa -out root-ca-key.pem 2048
              openssl req -new -x509 -sha256 -key root-ca-key.pem -out root-ca.pem -days 3650 \
                -subj "/C=US/ST=California/L=California/O=Wazuh/OU=Wazuh/CN=root-ca"
              
              # Generate Admin certificate
              echo "2. Generating Admin certificate..."
              openssl genrsa -out admin-key.pem 2048
              openssl req -new -key admin-key.pem -out admin.csr \
                -subj "/C=US/ST=California/L=California/O=Wazuh/OU=Wazuh/CN=admin"
              openssl x509 -req -in admin.csr -CA root-ca.pem -CAkey root-ca-key.pem \
                -CAcreateserial -out admin.pem -days 3650 -sha256
              
              # Generate Indexer node certificate
              echo "3. Generating Indexer certificate..."
              openssl genrsa -out node-key.pem 2048
              openssl req -new -key node-key.pem -out node.csr \
                -subj "/C=US/ST=California/L=California/O=Wazuh/OU=Wazuh/CN=wazuh-indexer"
              
              cat > node.ext << EOF
              subjectAltName = DNS:wazuh-indexer,DNS:wazuh-indexer-0,DNS:wazuh-indexer-1,DNS:wazuh-indexer-2,DNS:wazuh-indexer.{{ include "wazuh.namespace" . }}.svc.cluster.local,DNS:localhost,IP:127.0.0.1
              EOF
              
              openssl x509 -req -in node.csr -CA root-ca.pem -CAkey root-ca-key.pem \
                -CAcreateserial -out node.pem -days 3650 -sha256 -extfile node.ext
              
              # Generate Filebeat certificate
              echo "4. Generating Filebeat certificate..."
              openssl genrsa -out filebeat-key.pem 2048
              openssl req -new -key filebeat-key.pem -out filebeat.csr \
                -subj "/C=US/ST=California/L=California/O=Wazuh/OU=Wazuh/CN=filebeat"
              openssl x509 -req -in filebeat.csr -CA root-ca.pem -CAkey root-ca-key.pem \
                -CAcreateserial -out filebeat.pem -days 3650 -sha256
              
              # Generate Dashboard certificate
              echo "5. Generating Dashboard certificate..."
              openssl genrsa -out dashboard-key.pem 2048
              openssl req -new -key dashboard-key.pem -out dashboard.csr \
                -subj "/C=US/ST=California/L=California/O=Wazuh/OU=Wazuh/CN=wazuh-dashboard"
              
              cat > dashboard.ext << EOF
              subjectAltName = DNS:wazuh-dashboard,DNS:wazuh-dashboard.{{ include "wazuh.namespace" . }}.svc.cluster.local,DNS:localhost,IP:127.0.0.1
              EOF
              
              openssl x509 -req -in dashboard.csr -CA root-ca.pem -CAkey root-ca-key.pem \
                -CAcreateserial -out dashboard.pem -days 3650 -sha256 -extfile dashboard.ext
              
              echo "All certificates generated successfully!"
              
              # Install kubectl
              echo "Installing kubectl..."
              apk add --no-cache curl
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/
              
              # Create secrets
              echo "Creating Kubernetes secrets..."
              
              # Indexer certs secret
              kubectl create secret generic indexer-certs \
                --from-file=root-ca.pem \
                --from-file=node.pem \
                --from-file=node-key.pem \
                --from-file=admin.pem \
                --from-file=admin-key.pem \
                --from-file=filebeat.pem \
                --from-file=filebeat-key.pem \
                --namespace={{ include "wazuh.namespace" . }} \
                --dry-run=client -o yaml | kubectl apply -f -
              
              # Dashboard certs secret
              kubectl create secret generic dashboard-certs \
                --from-file=cert.pem=dashboard.pem \
                --from-file=key.pem=dashboard-key.pem \
                --from-file=root-ca.pem \
                --namespace={{ include "wazuh.namespace" . }} \
                --dry-run=client -o yaml | kubectl apply -f -
              
              echo "Secrets created successfully!"
              echo "Certificate generation completed!"
          env:
            - name: NAMESPACE
              value: {{ include "wazuh.namespace" . }}
