apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "wazuh.namespace" . }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
