{{- if .Values.wazuhIndexer.enabled }}
apiVersion: {{ include "wazuh.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: {{ include "wazuh.namespace" . }}
  labels:
    {{- include "wazuh.indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wazuhIndexer.replicas }}
  serviceName: wazuh-indexer
  selector:
    matchLabels:
      {{- include "wazuh.indexer.selectorLabels" . | nindent 6 }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        {{- include "wazuh.indexer.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets/secrets.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wazuh.serviceAccountName" . }}
      {{- with .Values.wazuhIndexer.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: volume-mount-hack
          image: busybox:1.36
          command:
            - sh
            - '-c'
            - 'chown -R 1000:1000 /var/lib/wazuh-indexer'
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
        - name: increase-the-vm-max-map-count
          image: busybox:1.36
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      volumes:
        - name: indexer-certs
          secret:
            secretName: indexer-certs
        - name: indexer-conf
          configMap:
            name: indexer-conf
      containers:
        - name: wazuh-indexer
          image: "{{ .Values.wazuhIndexer.image.repository }}:{{ .Values.wazuhIndexer.image.tag }}"
          imagePullPolicy: {{ .Values.wazuhIndexer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: {{ .Values.wazuhIndexer.opensearchConfig.javaOpts | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.wazuhIndexer.opensearchConfig.clusterName | quote }}
            - name: NETWORK_HOST
              value: {{ .Values.wazuhIndexer.opensearchConfig.networkHost | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: wazuh-indexer
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/node-key.pem
              subPath: node-key.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/node.pem
              subPath: node.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/admin.pem
              subPath: admin.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/admin-key.pem
              subPath: admin-key.pem
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch.yml
              subPath: opensearch.yml
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch-security/internal_users.yml
              subPath: internal_users.yml
              readOnly: true
          {{- with .Values.wazuhIndexer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      {{- with .Values.wazuhIndexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wazuhIndexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wazuhIndexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.wazuhIndexer.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: wazuh-indexer
        labels:
          {{- include "wazuh.indexer.labels" . | nindent 10 }}
        {{- with .Values.wazuhIndexer.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.wazuhIndexer.persistence.accessModes | nindent 10 }}
        {{- if .Values.wazuhIndexer.persistence.storageClass }}
        storageClassName: {{ .Values.wazuhIndexer.persistence.storageClass }}
        {{- else if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.wazuhIndexer.persistence.size }}
  {{- end }}
{{- end }}
